# filebeat.autodiscover:
#   providers:
#     - type: docker
#       labels.dedot: true
#       templates:
#         - condition:
#             contains:
#               container.labels.collect_logs_with_filebeat: "true"
#           config:
#             - type: container
#               format: docker
#               paths:
#                 - "/var/lib/docker/containers/*.log"
#               processors:
#                 - decode_json_fields:
#                     when.equals:
#                       docker.container.labels.decode_log_event_to_json_object: "true"
#                     fields: ["message"]
#                     target: ""
#                     overwrite_keys: true

filebeat.inputs:
- type: log
  paths:
    - /var/lib/docker/containers/*.log

output.logstash:
  hosts: "logstash:5044"

logging.metrics.enabled: false
