version: '3'
services:
  blog:
    build:
      context: ./blog
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - "./volumes/logs:/app/logs"
    networks:
      - app

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./volumes/prometheus/app-prom.yml:/etc/prometheus/prometheus.yml"
    networks:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - "./volumes/grafana-blog-vol/prom_db/data:/var/lib/grafana"
    networks:
      - app

  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - "./volumes/elastic-blog-vol/data01:/usr/share/elasticsearch/data:rw"

  logstash:
    image: logstash:7.6.2
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./volumes/logstash/pipeline:/usr/share/logstash/pipeline:ro
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.6.2
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    image: elastic/filebeat:7.9.0
    volumes:
      - ./volumes/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro        # Configuration file
      - ./volumes/logs/:/var/lib/docker/containers:ro                                      # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                              # Additional information about containers
      - "./volumes/filebeat-blog-vol/data01:/usr/share/filebeat/data:rw"     # Persistence data
    user: root                                                                    # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash
      - elasticsearch

networks:
  app:
    driver: bridge
