global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus_blog'
    metrics_path: 'blog/v1/management/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9001']
      - labels:
          group: prometheus_blog
